#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_demo
#    username: root
#    password: root
#    driverClassName: com.mysql.jdbc.Driver
#  jpa:
#    database: MYSQL
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#